apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-one
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: guestbook-one
    name: staging-01
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
